/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.awt.Color;

/**
 *
 * @author daniel
 */
public class HomePage extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                        .getLogger(HomePage.class.getName());

        /**
         * Creates new form HomePage
         */

        Color mouseEnterColor = new Color(0, 0, 0);
        Color mouseExitColor = new Color(51, 51, 51);
        public HomePage() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPnlHeader = new javax.swing.JPanel();
        lblIconMenu = new javax.swing.JLabel();
        JPnlHeaderSpacer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JPnlSideBar = new javax.swing.JPanel();
        JPnlHomePage = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        JPnlDashboard = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        lblFeaturesTxt = new javax.swing.JLabel();
        JPnlManageBooks = new javax.swing.JPanel();
        lblManageBooksTxt = new javax.swing.JLabel();
        JPnlManageStudents = new javax.swing.JPanel();
        lblDashboard3 = new javax.swing.JLabel();
        JPnlReturnBook = new javax.swing.JPanel();
        lblReturnBookTxt = new javax.swing.JLabel();
        JPnlIssueBook = new javax.swing.JPanel();
        lblIssueBookTxt1 = new javax.swing.JLabel();
        JPnlViewRecords = new javax.swing.JPanel();
        lblViewRecordsTxt = new javax.swing.JLabel();
        JPnlViewIssuedBook = new javax.swing.JPanel();
        lblViewIssuedBooksTxt = new javax.swing.JLabel();
        JPnlDefaultList = new javax.swing.JPanel();
        lblDefaultListTxt = new javax.swing.JLabel();
        JPnlLogout = new javax.swing.JPanel();
        lblLogoutTxt = new javax.swing.JLabel();
        JPnlDetailSection = new javax.swing.JPanel();
        JPnlNoStudents = new javax.swing.JPanel();
        lblNoStudetntsNum = new javax.swing.JLabel();
        lblNoStudentsTxt = new javax.swing.JLabel();
        lblNoBooksTxt = new javax.swing.JLabel();
        JPnlNoBooks = new javax.swing.JPanel();
        lblNoBooksNum = new javax.swing.JLabel();
        lblIssuedBooksTxt = new javax.swing.JLabel();
        JPnlIssuedBooks = new javax.swing.JPanel();
        lblIssuedBooksNum = new javax.swing.JLabel();
        lblNoStudentsTxt3 = new javax.swing.JLabel();
        JPnlNoStudents3 = new javax.swing.JPanel();
        lblNoStudetntsNum3 = new javax.swing.JLabel();
        lblStudentDetailsHeader = new javax.swing.JLabel();
        jScrollPaneStudentDetails = new javax.swing.JScrollPane();
        rSTableStudentDetails = new rojerusan.RSTableMetro();
        lblBookDetailsHeader = new javax.swing.JLabel();
        jScrollPaneBookDetails = new javax.swing.JScrollPane();
        rSTableBookDetails = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(1541, 828));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPnlHeader.setBackground(new java.awt.Color(102, 102, 255));
        JPnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        JPnlHeader.add(lblIconMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        JPnlHeaderSpacer.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout JPnlHeaderSpacerLayout = new javax.swing.GroupLayout(JPnlHeaderSpacer);
        JPnlHeaderSpacer.setLayout(JPnlHeaderSpacerLayout);
        JPnlHeaderSpacerLayout.setHorizontalGroup(
            JPnlHeaderSpacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        JPnlHeaderSpacerLayout.setVerticalGroup(
            JPnlHeaderSpacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        JPnlHeader.add(JPnlHeaderSpacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 5, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel1.setText("Welcome, Admin");
        JPnlHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, 270, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Library Management System");
        JPnlHeader.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        getContentPane().add(JPnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 1540, 70));

        JPnlSideBar.setBackground(new java.awt.Color(51, 51, 51));
        JPnlSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPnlHomePage.setBackground(new java.awt.Color(255, 51, 51));
        JPnlHomePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel5.setText("    Home Page");
        JPnlHomePage.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel6.setText("    Home Page");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        JPnlHomePage.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 340, 60));

        JPnlSideBar.add(JPnlHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 60));

        JPnlDashboard.setBackground(new java.awt.Color(51, 51, 51));
        JPnlDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDashboard.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(153, 153, 153));
        lblDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        lblDashboard.setText("    Dashboard");
        JPnlDashboard.add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        JPnlSideBar.add(JPnlDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 340, 60));

        lblFeaturesTxt.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblFeaturesTxt.setForeground(new java.awt.Color(255, 255, 255));
        lblFeaturesTxt.setText("Features");
        JPnlSideBar.add(lblFeaturesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        JPnlManageBooks.setBackground(new java.awt.Color(51, 51, 51));
        JPnlManageBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblManageBooksTxt.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblManageBooksTxt.setForeground(new java.awt.Color(153, 153, 153));
        lblManageBooksTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        lblManageBooksTxt.setText("    Manage Books");
        lblManageBooksTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblManageBooksTxtFocusGained(evt);
            }
        });
        lblManageBooksTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageBooksTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblManageBooksTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblManageBooksTxtMouseExited(evt);
            }
        });
        JPnlManageBooks.add(lblManageBooksTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        JPnlSideBar.add(JPnlManageBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 340, 60));

        JPnlManageStudents.setBackground(new java.awt.Color(51, 51, 51));
        JPnlManageStudents.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDashboard3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblDashboard3.setForeground(new java.awt.Color(153, 153, 153));
        lblDashboard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        lblDashboard3.setText("    Manage Students");
        lblDashboard3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDashboard3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDashboard3MouseExited(evt);
            }
        });
        JPnlManageStudents.add(lblDashboard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        JPnlSideBar.add(JPnlManageStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 340, 60));

        JPnlReturnBook.setBackground(new java.awt.Color(51, 51, 51));
        JPnlReturnBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReturnBookTxt.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblReturnBookTxt.setForeground(new java.awt.Color(153, 153, 153));
        lblReturnBookTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        lblReturnBookTxt.setText("    Return Book");
        lblReturnBookTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReturnBookTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReturnBookTxtMouseExited(evt);
            }
        });
        JPnlReturnBook.add(lblReturnBookTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        JPnlSideBar.add(JPnlReturnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 340, 60));

        JPnlIssueBook.setBackground(new java.awt.Color(51, 51, 51));
        JPnlIssueBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIssueBookTxt1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblIssueBookTxt1.setForeground(new java.awt.Color(153, 153, 153));
        lblIssueBookTxt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
        lblIssueBookTxt1.setText("    Issue Book");
        lblIssueBookTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIssueBookTxt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIssueBookTxt1MouseExited(evt);
            }
        });
        JPnlIssueBook.add(lblIssueBookTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        JPnlSideBar.add(JPnlIssueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 340, 60));

        JPnlViewRecords.setBackground(new java.awt.Color(51, 51, 51));
        JPnlViewRecords.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewRecordsTxt.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblViewRecordsTxt.setForeground(new java.awt.Color(153, 153, 153));
        lblViewRecordsTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
        lblViewRecordsTxt.setText("    View Records");
        lblViewRecordsTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewRecordsTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewRecordsTxtMouseExited(evt);
            }
        });
        JPnlViewRecords.add(lblViewRecordsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        JPnlSideBar.add(JPnlViewRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 340, 60));

        JPnlViewIssuedBook.setBackground(new java.awt.Color(51, 51, 51));
        JPnlViewIssuedBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewIssuedBooksTxt.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblViewIssuedBooksTxt.setForeground(new java.awt.Color(153, 153, 153));
        lblViewIssuedBooksTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Books_26px.png"))); // NOI18N
        lblViewIssuedBooksTxt.setText("    View Issued Books");
        lblViewIssuedBooksTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewIssuedBooksTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewIssuedBooksTxtMouseExited(evt);
            }
        });
        JPnlViewIssuedBook.add(lblViewIssuedBooksTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        JPnlSideBar.add(JPnlViewIssuedBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 340, 60));

        JPnlDefaultList.setBackground(new java.awt.Color(51, 51, 51));
        JPnlDefaultList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDefaultListTxt.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblDefaultListTxt.setForeground(new java.awt.Color(153, 153, 153));
        lblDefaultListTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        lblDefaultListTxt.setText("    Default List");
        lblDefaultListTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDefaultListTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDefaultListTxtMouseExited(evt);
            }
        });
        JPnlDefaultList.add(lblDefaultListTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        JPnlSideBar.add(JPnlDefaultList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 340, 60));

        JPnlLogout.setBackground(new java.awt.Color(102, 102, 255));
        JPnlLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoutTxt.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblLogoutTxt.setForeground(new java.awt.Color(255, 255, 255));
        lblLogoutTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        lblLogoutTxt.setText("    Logout");
        JPnlLogout.add(lblLogoutTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        JPnlSideBar.add(JPnlLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 340, 60));

        getContentPane().add(JPnlSideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 340, 760));

        JPnlDetailSection.setBackground(new java.awt.Color(255, 255, 255));
        JPnlDetailSection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPnlNoStudents.setBackground(new java.awt.Color(204, 204, 204));
        JPnlNoStudents.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));

        lblNoStudetntsNum.setBackground(new java.awt.Color(102, 102, 102));
        lblNoStudetntsNum.setFont(new java.awt.Font("Liberation Sans", 1, 50)); // NOI18N
        lblNoStudetntsNum.setForeground(new java.awt.Color(102, 102, 102));
        lblNoStudetntsNum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        lblNoStudetntsNum.setText("100");

        javax.swing.GroupLayout JPnlNoStudentsLayout = new javax.swing.GroupLayout(JPnlNoStudents);
        JPnlNoStudents.setLayout(JPnlNoStudentsLayout);
        JPnlNoStudentsLayout.setHorizontalGroup(
            JPnlNoStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlNoStudentsLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblNoStudetntsNum)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        JPnlNoStudentsLayout.setVerticalGroup(
            JPnlNoStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlNoStudentsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblNoStudetntsNum)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        JPnlDetailSection.add(JPnlNoStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 260, 140));

        lblNoStudentsTxt.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblNoStudentsTxt.setForeground(new java.awt.Color(0, 0, 0));
        lblNoStudentsTxt.setText("No. Of Students");
        JPnlDetailSection.add(lblNoStudentsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblNoBooksTxt.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblNoBooksTxt.setForeground(new java.awt.Color(0, 0, 0));
        lblNoBooksTxt.setText("No. Of Books");
        JPnlDetailSection.add(lblNoBooksTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        JPnlNoBooks.setBackground(new java.awt.Color(204, 204, 204));
        JPnlNoBooks.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(102, 102, 255)));

        lblNoBooksNum.setBackground(new java.awt.Color(102, 102, 102));
        lblNoBooksNum.setFont(new java.awt.Font("Liberation Sans", 1, 50)); // NOI18N
        lblNoBooksNum.setForeground(new java.awt.Color(102, 102, 102));
        lblNoBooksNum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        lblNoBooksNum.setText("100");

        javax.swing.GroupLayout JPnlNoBooksLayout = new javax.swing.GroupLayout(JPnlNoBooks);
        JPnlNoBooks.setLayout(JPnlNoBooksLayout);
        JPnlNoBooksLayout.setHorizontalGroup(
            JPnlNoBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlNoBooksLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblNoBooksNum)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        JPnlNoBooksLayout.setVerticalGroup(
            JPnlNoBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlNoBooksLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblNoBooksNum)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        JPnlDetailSection.add(JPnlNoBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 260, 140));

        lblIssuedBooksTxt.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblIssuedBooksTxt.setForeground(new java.awt.Color(0, 0, 0));
        lblIssuedBooksTxt.setText("Issued Books");
        JPnlDetailSection.add(lblIssuedBooksTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        JPnlIssuedBooks.setBackground(new java.awt.Color(204, 204, 204));
        JPnlIssuedBooks.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));

        lblIssuedBooksNum.setBackground(new java.awt.Color(102, 102, 102));
        lblIssuedBooksNum.setFont(new java.awt.Font("Liberation Sans", 1, 50)); // NOI18N
        lblIssuedBooksNum.setForeground(new java.awt.Color(102, 102, 102));
        lblIssuedBooksNum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_50px.png"))); // NOI18N
        lblIssuedBooksNum.setText("100");

        javax.swing.GroupLayout JPnlIssuedBooksLayout = new javax.swing.GroupLayout(JPnlIssuedBooks);
        JPnlIssuedBooks.setLayout(JPnlIssuedBooksLayout);
        JPnlIssuedBooksLayout.setHorizontalGroup(
            JPnlIssuedBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlIssuedBooksLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblIssuedBooksNum)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        JPnlIssuedBooksLayout.setVerticalGroup(
            JPnlIssuedBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlIssuedBooksLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblIssuedBooksNum)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        JPnlDetailSection.add(JPnlIssuedBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 260, 140));

        lblNoStudentsTxt3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblNoStudentsTxt3.setForeground(new java.awt.Color(0, 0, 0));
        lblNoStudentsTxt3.setText("Default List");
        JPnlDetailSection.add(lblNoStudentsTxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        JPnlNoStudents3.setBackground(new java.awt.Color(204, 204, 204));
        JPnlNoStudents3.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(102, 102, 255)));

        lblNoStudetntsNum3.setBackground(new java.awt.Color(102, 102, 102));
        lblNoStudetntsNum3.setFont(new java.awt.Font("Liberation Sans", 1, 50)); // NOI18N
        lblNoStudetntsNum3.setForeground(new java.awt.Color(102, 102, 102));
        lblNoStudetntsNum3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        lblNoStudetntsNum3.setText("100");

        javax.swing.GroupLayout JPnlNoStudents3Layout = new javax.swing.GroupLayout(JPnlNoStudents3);
        JPnlNoStudents3.setLayout(JPnlNoStudents3Layout);
        JPnlNoStudents3Layout.setHorizontalGroup(
            JPnlNoStudents3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlNoStudents3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblNoStudetntsNum3)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        JPnlNoStudents3Layout.setVerticalGroup(
            JPnlNoStudents3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlNoStudents3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblNoStudetntsNum3)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        JPnlDetailSection.add(JPnlNoStudents3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 260, 140));

        lblStudentDetailsHeader.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblStudentDetailsHeader.setForeground(new java.awt.Color(0, 0, 0));
        lblStudentDetailsHeader.setText("Student Details");
        JPnlDetailSection.add(lblStudentDetailsHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        rSTableStudentDetails.setBackground(new java.awt.Color(204, 204, 204));
        rSTableStudentDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"test", null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Id", "Name", "Course", "Branch"
            }
        ));
        rSTableStudentDetails.setRowHeight(25);
        jScrollPaneStudentDetails.setViewportView(rSTableStudentDetails);

        JPnlDetailSection.add(jScrollPaneStudentDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 550, 150));

        lblBookDetailsHeader.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblBookDetailsHeader.setForeground(new java.awt.Color(0, 0, 0));
        lblBookDetailsHeader.setText("Book Details");
        JPnlDetailSection.add(lblBookDetailsHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        rSTableBookDetails.setBackground(new java.awt.Color(204, 204, 204));
        rSTableBookDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"test", null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Id", "Name", "Course", "Branch"
            }
        ));
        rSTableBookDetails.setRowHeight(25);
        jScrollPaneBookDetails.setViewportView(rSTableBookDetails);

        JPnlDetailSection.add(jScrollPaneBookDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 550, 150));

        getContentPane().add(JPnlDetailSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 1200, 760));

        setSize(new java.awt.Dimension(1532, 865));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblManageBooksTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageBooksTxtMouseEntered
        JPnlManageBooks.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lblManageBooksTxtMouseEntered

    private void lblManageBooksTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageBooksTxtMouseExited
       JPnlManageBooks.setBackground(mouseExitColor);
    }//GEN-LAST:event_lblManageBooksTxtMouseExited

    private void lblDashboard3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboard3MouseEntered
        JPnlManageStudents.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lblDashboard3MouseEntered

    private void lblDashboard3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboard3MouseExited
        JPnlManageStudents.setBackground(mouseExitColor);
    }//GEN-LAST:event_lblDashboard3MouseExited

    private void lblReturnBookTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnBookTxtMouseExited
        JPnlReturnBook.setBackground(mouseExitColor);
    }//GEN-LAST:event_lblReturnBookTxtMouseExited

    private void lblReturnBookTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnBookTxtMouseEntered
        JPnlReturnBook.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lblReturnBookTxtMouseEntered

    private void lblIssueBookTxt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIssueBookTxt1MouseEntered
        JPnlIssueBook.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lblIssueBookTxt1MouseEntered

    private void lblIssueBookTxt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIssueBookTxt1MouseExited
        JPnlIssueBook.setBackground(mouseExitColor);
    }//GEN-LAST:event_lblIssueBookTxt1MouseExited

    private void lblViewRecordsTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewRecordsTxtMouseEntered
        JPnlViewRecords.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lblViewRecordsTxtMouseEntered

    private void lblViewRecordsTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewRecordsTxtMouseExited
        JPnlViewRecords.setBackground(mouseExitColor);
    }//GEN-LAST:event_lblViewRecordsTxtMouseExited

    private void lblViewIssuedBooksTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewIssuedBooksTxtMouseEntered
        JPnlViewIssuedBook.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lblViewIssuedBooksTxtMouseEntered

    private void lblViewIssuedBooksTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewIssuedBooksTxtMouseExited
        JPnlViewIssuedBook.setBackground(mouseExitColor);
    }//GEN-LAST:event_lblViewIssuedBooksTxtMouseExited

    private void lblDefaultListTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDefaultListTxtMouseEntered
        JPnlDefaultList.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lblDefaultListTxtMouseEntered

    private void lblDefaultListTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDefaultListTxtMouseExited
        JPnlDefaultList.setBackground(mouseExitColor);
    }//GEN-LAST:event_lblDefaultListTxtMouseExited

    
        private void lblManageBooksTxtMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblManageBooksTxtMouseClicked
                ManageBooks managedBooks = new ManageBooks();
                managedBooks.setVisible(true);
                dispose();
        }// GEN-LAST:event_lblManageBooksTxtMouseClicked

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                        logger.log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> new HomePage().setVisible(true));
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPnlDashboard;
    private javax.swing.JPanel JPnlDefaultList;
    private javax.swing.JPanel JPnlDetailSection;
    private javax.swing.JPanel JPnlHeader;
    private javax.swing.JPanel JPnlHeaderSpacer;
    private javax.swing.JPanel JPnlHomePage;
    private javax.swing.JPanel JPnlIssueBook;
    private javax.swing.JPanel JPnlIssuedBooks;
    private javax.swing.JPanel JPnlLogout;
    private javax.swing.JPanel JPnlManageBooks;
    private javax.swing.JPanel JPnlManageStudents;
    private javax.swing.JPanel JPnlNoBooks;
    private javax.swing.JPanel JPnlNoStudents;
    private javax.swing.JPanel JPnlNoStudents3;
    private javax.swing.JPanel JPnlReturnBook;
    private javax.swing.JPanel JPnlSideBar;
    private javax.swing.JPanel JPnlViewIssuedBook;
    private javax.swing.JPanel JPnlViewRecords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPaneBookDetails;
    private javax.swing.JScrollPane jScrollPaneStudentDetails;
    private javax.swing.JLabel lblBookDetailsHeader;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDashboard3;
    private javax.swing.JLabel lblDefaultListTxt;
    private javax.swing.JLabel lblFeaturesTxt;
    private javax.swing.JLabel lblIconMenu;
    private javax.swing.JLabel lblIssueBookTxt1;
    private javax.swing.JLabel lblIssuedBooksNum;
    private javax.swing.JLabel lblIssuedBooksTxt;
    private javax.swing.JLabel lblLogoutTxt;
    private javax.swing.JLabel lblManageBooksTxt;
    private javax.swing.JLabel lblNoBooksNum;
    private javax.swing.JLabel lblNoBooksTxt;
    private javax.swing.JLabel lblNoStudentsTxt;
    private javax.swing.JLabel lblNoStudentsTxt3;
    private javax.swing.JLabel lblNoStudetntsNum;
    private javax.swing.JLabel lblNoStudetntsNum3;
    private javax.swing.JLabel lblReturnBookTxt;
    private javax.swing.JLabel lblStudentDetailsHeader;
    private javax.swing.JLabel lblViewIssuedBooksTxt;
    private javax.swing.JLabel lblViewRecordsTxt;
    private rojerusan.RSTableMetro rSTableBookDetails;
    private rojerusan.RSTableMetro rSTableStudentDetails;
    // End of variables declaration//GEN-END:variables
}
