/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class LoginPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(LoginPage.class.getName());

    /**
     * Creates new form SignupPage
     */

    public LoginPage() {
        initComponents();
    }

    // methods to insert values into user table
    public void insertSignupDetaisl() {
        String name = txtFieldUserName.getText();
        String pwd = txtFieldPassword.getText();

        try {
            Connection conn = DBConnection.getConnection();
            String sql = "INSERT INTO library_ms.users (username, password) VALUES(?,?)";

            PreparedStatement prepStatement = conn.prepareStatement(sql);
            prepStatement.setString(1, name);
            prepStatement.setString(2, pwd);

            int updatedRowCount = prepStatement.executeUpdate();

            if (updatedRowCount > 0) {
                JOptionPane.showMessageDialog(this, "User Successfuly Created");
                txtFieldUserName.setText("");
                txtFieldUserName.setForeground(getForeground());
                txtFieldPassword.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Unable to Create new user");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // ###########! VALIDATION !########## ->

    // validate login fields
    public boolean LoginFieldsFilled() {
        boolean allFieldFilled = false;
        String username = txtFieldUserName.getText();
        String password = txtFieldPassword.getText();

        if (username.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Username");
            allFieldFilled = false;
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Password");
            allFieldFilled = false;
        } else {
            allFieldFilled = true;
        }
        return allFieldFilled;
    }

    // validate login credentials
    public void validateLogin() {
        String username = txtFieldUserName.getText();
        String password = txtFieldPassword.getText();

        try {
            Connection conn = DBConnection.getConnection();

            String sqlQuery = "SELECT * FROM library_ms.users WHERE username = ? and password = ?";

            PreparedStatement prepStatment = conn.prepareStatement(sqlQuery);
            prepStatment.setString(1, username);
            prepStatment.setString(2, password);

            ResultSet rs = prepStatment.executeQuery();

            if (rs.next()) {
                HomePage home = new HomePage();
                home.setVisible(true);
                this.dispose();
                // TODO: call HomePage
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Username or Password");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // check duplicate users
    public boolean checkDuplicateUser() {
        boolean userExists = false;
        String username = txtFieldUserName.getText();

        try {
            Connection conn = DBConnection.getConnection();

            String sqlQuery = "SELECT * FROM library_ms.users WHERE username = ?";
            PreparedStatement prepStatment = conn.prepareStatement(sqlQuery);
            prepStatment.setString(1, username);
            ResultSet rs = prepStatment.executeQuery();
            if (rs.next()) {
                userExists = true;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return userExists;
    }

    // <- ###########! VALIDATION !##########

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAdvanceLibrary = new javax.swing.JLabel();
        lblLibraryImage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblWelcomeMsg = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        txtFieldUserName = new javax.swing.JTextField();
        lblAcountIcon = new javax.swing.JLabel();
        lblPassIcon = new javax.swing.JLabel();
        txtFieldPassword = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdvanceLibrary.setFont(new java.awt.Font("Liberation Sans", 0, 45)); // NOI18N
        lblAdvanceLibrary.setForeground(new java.awt.Color(102, 102, 255));
        lblAdvanceLibrary.setText("School Library Manager");
        jPanel1.add(lblAdvanceLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 490, -1));

        lblLibraryImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/stackedBooks.png"))); // NOI18N
        jPanel1.add(lblLibraryImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 780, 580));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcomeMsg.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        lblWelcomeMsg.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeMsg.setText("Login or create new acount");
        jPanel2.add(lblWelcomeMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 230, -1));

        lblWelcome.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Welcome");
        jPanel2.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 210, -1));

        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("UserName");
        jPanel2.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 170, -1));

        txtFieldUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldUserNameFocusLost(evt);
            }
        });
        txtFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldUserNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtFieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 260, 30));

        lblAcountIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel2.add(lblAcountIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        lblPassIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secure_50px.png"))); // NOI18N
        jPanel2.add(lblPassIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        txtFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 260, 30));

        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        jPanel2.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 170, -1));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 260, -1));

        btnSignup.setText("Sign Up");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        jPanel2.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1532, 865));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldUserNameFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtFieldUserNameFocusLost
        checkDuplicateUser();
    }// GEN-LAST:event_txtFieldUserNameFocusLost

    private void txtFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtFieldUserNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtFieldUserNameActionPerformed

    private void txtFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtFieldPasswordActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtFieldPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLoginActionPerformed
        if (LoginFieldsFilled()) {
            validateLogin();
        }

    }// GEN-LAST:event_btnLoginActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSignupActionPerformed
        if (checkDuplicateUser()) {
            JOptionPane.showMessageDialog(this, "Username already exists!");
        } else {
            insertSignupDetaisl();
        }
    }// GEN-LAST:event_btnSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAcountIcon;
    private javax.swing.JLabel lblAdvanceLibrary;
    private javax.swing.JLabel lblLibraryImage;
    private javax.swing.JLabel lblPassIcon;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcomeMsg;
    private javax.swing.JTextField txtFieldPassword;
    private javax.swing.JTextField txtFieldUserName;
    // End of variables declaration//GEN-END:variables
}
